---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: renovatebot
    namespace: renovatebot
spec:
    interval: 3m
    url: https://docs.renovatebot.com/helm-charts
