---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: traefik-release
    namespace: traefik
spec:
    interval: 1m
    install:
        crds: Skip
    chart:
        spec:
            chart: traefik
            sourceRef:
                kind: GitRepository
                name: traefik-helm-chart
            interval: 1m
    values:
        hub:
            enabled: false
        ingressClass:
            enabled: true
            isDefaultClass: true
        ingressRoute:
            dashboard:
                enabled: true
        ports:
            traefik:
                expose: true
