---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: renovatebot
    namespace: renovatebot
spec:
    interval: 1m
    chart:
        spec:
            chart: renovate
            version: 34.17.1
            sourceRef:
                kind: HelmRepository
                name: renovatebot
            interval: 1m
    values:
        cronjob:
            schedule: '@hourly'
            concurrencyPolicy: Forbid
        renovate:
            config: |
                {
                    "platform": "github",
                    "username": "5cat",
                    "gitAuthor": "Renovate Bot <renovate@heaven.ist>",
                    "repositories": ["5cat/home-root-cluster"]
                }
        dind:
            enabled: true
        existingSecret: renovate-secrets  # pragma: allowlist secret
