---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: apps
    namespace: flux-system
spec:
    dependsOn:
        - name: cores
    interval: 1m
    path: ./kubernetes/apps
    prune: true
    sourceRef:
        kind: GitRepository
        name: home-root-cluster
    decryption:
        provider: sops
        secretRef:
            name: sops-age
