---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: sources
    namespace: flux-system
spec:
    dependsOn:
        - name: namespaces
    interval: 1m
    path: ./kubernetes/sources
    prune: true
    sourceRef:
        kind: GitRepository
        name: home-root-cluster
