---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: home-root-range
    namespace: metallb-system
spec:
    addresses:
        - 192.168.35.1-192.168.35.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
    name: l2adver
    namespace: metallb-system
