---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
    name: flux2
    namespace: flux-system
spec:
    interval: 30m
    ref:
        tag: v0.36.0
    url: https://github.com/fluxcd/flux2.git
    ignore: |
        # exclude all
        /*
        # path to manifests
        !/manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: flux-install
    namespace: flux-system
spec:
    interval: 30m
    path: ./manifests/install
    prune: true
    wait: true
    sourceRef:
        kind: GitRepository
        name: flux2
