---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: metallb
    namespace: metallb-system
spec:
    interval: 10m
    path: ./config/native
    prune: true
    wait: true
    sourceRef:
        kind: GitRepository
        name: metallb
    healthChecks:
        - apiVersion: apiextensions.k8s.io/v1
          kind: CustomResourceDefinition
          name: ipaddresspools.metallb.io
