---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
    name: traefik-helm-chart
    namespace: traefik
spec:
    interval: 30m
    url: https://github.com/traefik/traefik-helm-chart.git
    ref:
        tag: v19.0.3
    ignore: |
        # exclude all
        /*
        # path to crds
        !/traefik/
